plugins {
	id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
    id "me.modmuss50.mod-publish-plugin" version "0.7.4"
	id "com.modrinth.minotaur" version "2.+"
}
apply from: "main.gradle"

// Should exist on all loaders and is loader specific
repositories {
	maven {url "https://modmaven.dev/" }// UnionLib
	maven {url "https://www.cursemaven.com"} //CurseForge
    maven {url = "https://repo.spongepowered.org/maven"} // mixin
	maven {url "https://girafi.dk/maven/"}
	
	maven {url = "https://maven.theillusivec4.top/"}
	maven {url 'https://maven.blamejared.com'}
    maven {url "https://maven.shedaniel.me/"} // cloth config
}

dependencies {
	implementation ("net.neoforged:neoforge:${_loader_version}")
	
	implementation ("com.stereowalker.unionlib:UnionLib:${_minecraft_version}-${_unionlib_version}-${_loader}")
	
	compileOnly ("mezz.jei:jei-${_minecraft_version}-common-api:${_jei_version}")
	compileOnly ("mezz.jei:jei-${_minecraft_version}-neoforge-api:${_jei_version}")
	compileOnly ("com.stereowalker.combat:C.O.M.B.A.T:1.18.2"+/*_minecraft_version+*/"-"+combatVersion+":api")
    //compileOnly ("top.theillusivec4.caelus:caelus-forge:"+_minecraft_version+"-"+caelusVersion+"")
    //compileOnly ("vazkii.patchouli:Patchouli:${_minecraft_version}-${patchouliVersion}-FORGE:api")
	
	implementation ("mezz.jei:jei-${_minecraft_version}-neoforge:${_jei_version}")
	//runtimeOnly ("top.theillusivec4.caelus:caelus-forge:"+_minecraft_version+"-"+caelusVersion+"")
    //runtimeOnly ("vazkii.patchouli:Patchouli:${_minecraft_version}-${patchouliVersion}-FORGE")
	
    implementation ("com.github.glitchfiend:GlitchCore-neoforge:${_minecraft_version}-2.1.0.0")
    implementation ("com.github.glitchfiend:TerraBlender-neoforge:1.21-4.0.0.1")
    implementation ("com.github.glitchfiend:SereneSeasons-neoforge:1.21-${_serene_seasons_version}")
    implementation ("com.github.glitchfiend:BiomesOPlenty-neoforge:${_minecraft_version}-${_bop_version}")
	//implementation ("curse.maven:origins-474438:"+originsID)
	//implementation ("curse.maven:create-328085:"+createID)
	//implementation ("curse.maven:flywheel-486392:"+flywheelID)
	
	implementation "curse.maven:parcool-482378:5862895"
}

task apiJar(type: Jar) {
    from(sourceSets.main.allJava) {
        include 'com/stereowalker/survive/api/**'
    }
    from (sourceSets.main.output) {
        include 'com/stereowalker/survive/api/**'
    }
	archiveClassifier = 'api'
}
artifacts {
	archives apiJar
}
