# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false

neogradle.subsystems.parchment.minecraftVersion=1.20.6
neogradle.subsystems.parchment.mappingsVersion=2024.05.01

modLoader = NeoForge
mappingsVersion = 2024.07.07-1.21

modMixinVersion = 0.8.5
mappingsChannel = parchment

modVersion = 10.0.2
_mod_id = survive
modGroup = com.stereowalker.survive
_mod_name = Survive
modCurseId = 367337

unionLibVersion = 12.0.4
jeiVersion = 19.5.0.30
caelusVersion = 3.0.0.7
combatVersion = 9.0.5-beta
patchouliVersion = 81
_serene_seasons_version = 10.0.0.2
_bop_version = 21.0.0.12
originsID = 3941983
createID = 4174330
flywheelID = 4174759

## Environment Properties
_minecraft_version = 1.21
minecraft_version_range=[1.21,1.22)
_loader_version = 21.0.100-beta
_loader_version_min=4
_loader_version_max=5
forge_version_range=[0,)
## Mod Properties
_mod_license=CC BY-NC-ND 4.0
_mod_authors=Stereowalker
_mod_description=Adds new survival mechanics like thirst, body temperature, sleep management and stamina
