# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
#org.gradle.debug=false
neogradle.subsystems.parchment.minecraftVersion=1.21
neogradle.subsystems.parchment.mappingsVersion=2024.07.07
modMixinVersion = 0.8.5
mappingsChannel = parchment
modGroup = com.stereowalker.survive

## Publishing Porperties
_curseforge_id = 367337
_modrinth_id   = vg4qcCBb
## Environment Properties
_minecraft_version     = 1.21.1
_minecraft_version_min = 1.21
_minecraft_version_max = 1.22
_loader                = NeoForge
_loader_file           = META-INF/neoforge.mods.toml
_loader_version        = 21.1.60
_loader_version_min    = 4
_loader_version_max    = 5
_unionlib_version      = 12.0.13
_unionlib_version_min  = 12.0.13
_unionlib_version_max  = 12.1.0
## Mod Properties
_mod_name          = Survive
_mod_id            = survive
_mod_version       = 10.1.7
_mod_release       = release
_mod_environment   = client & server
_mod_license       = CC BY-NC-ND 4.0
_mod_authors       = Stereowalker
_mod_issue_tracker = https://github.com/Stereowalker/survive/issues
_mod_page          = https://www.stereowalker.com/survive
_mod_description   = Adds new survival mechanics like thirst, body temperature, sleep management and stamina
##Misc Properties
_jei_version = 19.8.5.118
caelusVersion = 3.0.0.7
combatVersion = 9.0.5-beta
patchouliVersion = 81
_serene_seasons_version = 10.0.0.2
_bop_version = 21.1.0.2
originsID = 3941983
createID = 4174330
flywheelID = 4174759
