java.toolchain.languageVersion = JavaLanguageVersion.of(_java_version.toInteger())
def resolvedCompiler = javaToolchains.compilerFor(java.toolchain).get()
def targetMeta = resolvedCompiler.metadata
layout.buildDirectory = file("build_${_minecraft_version}_${_loader}")
apply from: "${_loader}.gradle".toLowerCase()

println('Gradle Java: ' + System.getProperty('java.vm.version') + ' (' + System.getProperty('java.vendor') + ')' + ' (' + System.getProperty('java.version') + ')' + ' (' + System.getProperty('java.home') + ')')
println("Target Java: ${targetMeta.jvmVersion} (${targetMeta.vendor}) (${targetMeta.javaVersion}) (${targetMeta.installationPath})")
println('Arch: ' + System.getProperty('os.arch'))
println('Mod Name: ' + _mod_name + ', Mod Version: ' + _mod_version + ', Minecraft Version: ' + _minecraft_version + ', '+"${_loader} Version: " + _loader_version)

version = _minecraft_version + "-" +_mod_version +"-${_loader}"
group = _mod_group
base {
    archivesName = _mod_name
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            java_version: _java_version,
            minecraft_version: _minecraft_version,
            minecraft_version_min: _minecraft_version_min, minecraft_version_max: _minecraft_version_max,
            loader_version_min: _loader_version_min, loader_version_max: _loader_version_max,
            mod_page: _mod_page, mod_version: _mod_version, mod_issue_tracker: _mod_issue_tracker,
            mod_name: _mod_name, mod_license: _mod_license, mod_id: _mod_id, mod_entrypoint: _mod_entrypoint,
            mod_authors: _mod_authors, mod_description: _mod_description, loader_file: _loader_file,
            unionlib_version_min: _unionlib_version_min, unionlib_version_max: _unionlib_version_max,
    ]
    inputs.properties replaceProperties
    filesMatching([_loader_file, 'pack.mcmeta']) {
        expand replaceProperties// + [project: project]
    }
}


afterEvaluate {
	publishing {
		publications {
			mavenJava(MavenPublication) {
				afterEvaluate {
					artifacts.removeIf { it.classifier == null && it.extension == 'jar' }
					artifact tasks.named(project._mod_jar)
				}
				groupId = project.group
				artifactId = project._mod_name
				version = project.version
			}
		}
		repositories {
			maven {
				name = "modmaven"
				credentials {
					username "$System.env.ARTIFACTORYUSER"
					password "$System.env.ARTIFACTORYPASS"
				}
				url = "https://modmaven.dev/artifactory/local-releases/"
			}
		}
	}

	publishMods {
		curseforge {
			projectId = "${_curseforge_id}"
			accessToken = "$System.env.CURSEFORGEKEY"
			changelog = file('changelog.md').text
			changelogType = "markdown"
			if ("${_mod_release}" == "release") type = STABLE
			if ("${_mod_release}" == "beta") type = BETA
			if ("${_mod_release}" == "alpha") type = ALPHA
			"${_publish_minecraft_versions}".split(',').each { minecraftVersions.add(it.trim()) }
			"${_publish_mod_loaders}".split(',').each { modLoaders.add(it.trim()) }
			requires('unionlib')
			file = tasks.named(project._mod_jar).flatMap { task -> task.hasProperty('archiveFile') ? task.archiveFile : task.output }
			displayName = _mod_name+"-$project.version"
			/*mainArtifact(project._mod_jar) {
				displayName = _mod_name+"-$project.version"
			}*/
			if ("${_mod_environment}".contains('client')) clientRequired = true
			if ("${_mod_environment}".contains('server')) serverRequired = true
		}
	}

	modrinth {
		projectId = "${_modrinth_id}"
		token = "$System.env.MODRINTH_TOKEN"
		versionNumber = "${project.version}"
		versionType = "${_mod_release}"
		file = tasks.named(project._mod_jar).flatMap { task -> task.hasProperty('archiveFile') ? task.archiveFile : task.output }
		gameVersions = "${_publish_minecraft_versions}".split(',').collect { it.trim() }
		loaders = "${_publish_mod_loaders}".split(',').collect { it.trim().toLowerCase() }
		changelog = file('changelog.md').text
		dependencies {
			required.project "unionlib"
		}
	}
}

tasks.register('uploadToAllSites') {
	dependsOn "publishCurseforge"
	dependsOn "modrinth"
	group = "publishing"
	description = "Publishes to CurseForge and Modrinth"
}

tasks.register('uploadToAllSitesAndMaven') {
	dependsOn "publish"
	dependsOn "uploadToAllSites"
	group = "publishing"
	description = "Publishes to all sites and Maven"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
    it.options.release = _java_version.toInteger()
    options.compilerArgs += ['-parameters']
}
