
modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Stereowalker/survive/issues"
logoFile="logo.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Stereowalker/My-Home-Page/main/update_files/survive.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/survive"
credits="I'd like to thank all my supporters on Patreon for giving me a reason to continue modding, ChainmailPickaxe for the nice textures, and you for downloading and playing with this mod"
authors="${mod_authors}"
description='''${mod_description}'''
[[mixins]]
config="${mod_id}.mixins.json"
[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    modId="neoforge" #mandatory
    mandatory=true #mandatory
    versionRange="[21.0.0-beta,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="unionlib"
    mandatory=true
    versionRange="[12.0.0,13.0.0)"
    ordering="BEFORE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="sereneseasons"
    mandatory=false
    versionRange="[1.18.2-7.0.0.13,)"
    ordering="NONE"
    side="BOTH"
	

